version: '3'
services:
  bot:
    build: .
    restart: always
    links:
      - mongo
      - redis
  mongo:
    build: ./mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=senryu
    ports:
      - '27017:27017'
    volumes:
      - './db:/data/db'
  redis:
    restart: always
    image: redis:4.0-alpine
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command: ['redis-server', '--appendonly', 'yes']
