version: '3'
services:
  api:
    build: .
    restart: always
    links:
      - db
  db:
    build: ./mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=senryu
    volumes:
      - './db:/data/db'
